name: image_size_getter
description: Get image width and height, the library does not completely decode the image file, just read the metadata to get the image width and height.
version: 2.3.0
homepage: https://github.com/CaiJingLong/dart_image_size_getter

topics:
  - image
  - metadata
  - size
  - performance

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  hashcodes: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
