name: image_size_getter
description: Get image width and height, the library does not completely decode the image file, just read the metadata to get the image width and height.
version: 1.0.0-nullsafety
homepage: https://github.com/CaiJingLong/dart_image_size_getter/tree/master/library
# author: caijinglong <cjl_spy@163.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.14.12
  hashcodes:
    git:
      url: git://github.com/gskinnerTeam/dart_hashcodes.git
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
