name: dartdoc
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
        sdk:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Install dartdoc
        run: dart pub global activate dartdoc
      - name: Run dartdoc
        run: melos run dartdoc --no-select
